version: 2.1
orbs:
  ruby: circleci/ruby@1.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.1.10-node
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: "1.3.6"

  test:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.1.10-node
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test
      RACK_ENV: test
      APP_ENV: test
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: "1.3.6"
      - ruby/rspec-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
